"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image"; import Link from "next/link"; import dayjs from "dayjs";
import { ChevronLeft, ChevronRight, ClipboardPenLine, Loader2, Plus, Send, Trash2, X } from "lucide-react";
import logo from "../../../public/logo.png"; import LandingMenu from "../../components/LandingMenu";
import { addHandoff, deleteHandoff, loadHandoffs } from "../../lib/report-storage"; import type { HandoffRecord } from "../../types/handoff"; import styles from "./handoffs.module.css";

export default function HandoffsPage(){
 const [month,setMonth]=useState(()=>dayjs().format("YYYY-MM")),[date,setDate]=useState(()=>dayjs().format("YYYY-MM-DD")),[records,setRecords]=useState<HandoffRecord[]>([]);
 const [dayOpen,setDayOpen]=useState(false),[composing,setComposing]=useState(false),[author,setAuthor]=useState(""),[title,setTitle]=useState(""),[content,setContent]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{setRecords(await loadHandoffs(month))}catch(e){setError(e instanceof Error?e.message:"인수인계를 불러오지 못했습니다.")}finally{setLoading(false)}},[month]); useEffect(()=>{void refresh()},[refresh]);
 const days=useMemo(()=>{const start=dayjs(`${month}-01`).startOf("week");return Array.from({length:42},(_,i)=>start.add(i,"day"))},[month]); const daily=records.filter(r=>r.handoff_date===date);
 function move(n:number){const next=dayjs(`${month}-01`).add(n,"month");setMonth(next.format("YYYY-MM"));setDate(next.format("YYYY-MM-DD"))}
 async function submit(){if(!author.trim()||!title.trim()||!content.trim())return;setSaving(true);setError("");try{const saved=await addHandoff({id:crypto.randomUUID(),handoff_date:date,author:author.trim(),title:title.trim(),content:content.trim(),created_at:new Date().toISOString()});setRecords(v=>[saved,...v]);setTitle("");setContent("");setComposing(false)}catch(e){setError(e instanceof Error?e.message:"인수인계를 저장하지 못했습니다.")}finally{setSaving(false)}}
 async function remove(note:HandoffRecord){if(!window.confirm(`[${note.title}] 인수인계를 삭제할까요?\n삭제한 내용은 복구할 수 없습니다.`))return;setError("");try{await deleteHandoff(note.id);setRecords(v=>v.filter(item=>item.id!==note.id))}catch(e){setError(e instanceof Error?e.message:"인수인계를 삭제하지 못했습니다.")}}
 return <main className={styles.page}><header><div className={styles.identity}><Link href="/"><Image src={logo} alt="COSMATH" priority/></Link><span><ClipboardPenLine size={17}/> 인수인계</span></div><LandingMenu/></header><div className={styles.dashboard} data-handoff-dashboard>
 <section className={styles.calendar}><div className={styles.calendarHead}><button onClick={()=>move(-1)}><ChevronLeft/></button><h1>{dayjs(`${month}-01`).format("YYYY년 M월")}</h1><button onClick={()=>move(1)}><ChevronRight/></button></div><div className={styles.days}>{["일","월","화","수","목","금","토"].map(v=><small key={v}>{v}</small>)}{days.map(day=>{const key=day.format("YYYY-MM-DD"),count=records.filter(r=>r.handoff_date===key).length;return <button key={key} data-month={day.format("YYYY-MM")===month} data-selected={key===date} onClick={()=>{setDate(key);setDayOpen(true)}}><span>{day.date()}</span>{count>0&&<strong>{count}</strong>}</button>})}</div></section>
 {dayOpen&&<div className="fixed inset-0 z-40 grid place-items-center p-4 bg-slate-950/40 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)setDayOpen(false)}}><section className={`${styles.feed} relative w-full max-w-3xl max-h-[calc(100dvh-32px)] shadow-2xl`}><button className="absolute right-5 top-5 p-2 rounded-lg text-slate-500 hover:bg-slate-100" onClick={()=>setDayOpen(false)} aria-label="인수인계 목록 닫기"><X size={19}/></button><div className={styles.feedHead}><div><p>DAILY HANDOFF</p><h2>{dayjs(date).format("M월 D일")} 인수인계</h2></div><div className="flex items-center gap-2 mr-10"><span>{daily.length}건</span><button onClick={()=>setComposing(true)} className="p-2 text-[#2864a9] hover:bg-blue-50 rounded-lg" aria-label="새 인수인계 작성" title="새 인수인계 작성"><Plus size={19}/></button></div></div>{loading?<div className={styles.empty}><Loader2 className="animate-spin"/></div>:!daily.length?<div className={styles.empty}><ClipboardPenLine/><p>이 날짜에 등록된 인수인계가 없습니다.</p></div>:<div className={styles.notes}>{daily.map(note=><article key={note.id}><div><i>{note.author.slice(0,1)}</i><p><strong>{note.author}</strong><small>{dayjs(note.created_at).format("HH:mm")}</small></p><button className="ml-auto p-2 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50" onClick={()=>void remove(note)} aria-label={`${note.title} 삭제`}><Trash2 size={15}/></button></div><h3>{note.title}</h3><p>{note.content}</p></article>)}</div>}</section></div>}
 {composing&&<div className="fixed inset-0 z-50 grid place-items-center p-4 bg-slate-950/45 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setComposing(false)}}><aside className={`${styles.composer} relative w-full max-w-md max-h-[calc(100dvh-32px)] shadow-2xl`}><button className="absolute right-5 top-5 p-2 rounded-lg hover:bg-slate-100" onClick={()=>setComposing(false)} disabled={saving} aria-label="작성 창 닫기"><X size={18}/></button><p>NEW HANDOFF</p><h2>인수인계 작성</h2><span>{dayjs(date).format("YYYY년 M월 D일")}</span><label>작성자<input value={author} maxLength={100} onChange={e=>setAuthor(e.target.value)} placeholder="선생님 또는 조교 이름"/></label><label>제목<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)} placeholder="핵심 내용을 짧게 입력"/></label><label>내용<textarea value={content} maxLength={5000} onChange={e=>setContent(e.target.value)} placeholder="특이사항, 참고사항, 다음 담당자가 확인할 내용을 입력하세요."/></label>{error&&<div className={styles.error}>{error}</div>}<button disabled={saving||!author.trim()||!title.trim()||!content.trim()} onClick={()=>void submit()}>{saving?<Loader2 className="animate-spin"/>:<Send/>} 등록</button></aside></div>}
 </div></main>}
