"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Image from "next/image";import Link from "next/link";import dayjs from "dayjs";
import {ChevronLeft,ChevronRight,ClipboardPenLine,Loader2,Plus,Send,Trash2,X} from "lucide-react";
import logo from "../../../public/logo.png";import LandingMenu from "../../components/LandingMenu";
import {addHandoff,deleteHandoff,loadHandoffs} from "../../lib/report-storage";import type {HandoffRecord} from "../../types/handoff";import styles from "./handoffs.module.css";

export default function HandoffsPage(){
 const [month,setMonth]=useState(()=>dayjs().format("YYYY-MM")),[date,setDate]=useState(()=>dayjs().format("YYYY-MM-DD")),[records,setRecords]=useState<HandoffRecord[]>([]);
 const [composing,setComposing]=useState(false),[activeNote,setActiveNote]=useState<HandoffRecord|null>(null),[author,setAuthor]=useState(""),[title,setTitle]=useState(""),[content,setContent]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{setRecords(await loadHandoffs(month))}catch(e){setError(e instanceof Error?e.message:"인수인계를 불러오지 못했습니다.")}finally{setLoading(false)}},[month]);
 useEffect(()=>{void refresh()},[refresh]);
 const days=useMemo(()=>{const start=dayjs(`${month}-01`).startOf("week");return Array.from({length:42},(_,i)=>start.add(i,"day"))},[month]);
 const daily=records.filter(r=>r.handoff_date===date),activeDays=new Set(records.map(r=>r.handoff_date)).size;
 function move(n:number){const next=dayjs(`${month}-01`).add(n,"month");setMonth(next.format("YYYY-MM"));setDate(next.format("YYYY-MM-DD"));setActiveNote(null)}
 function goToday(){const today=dayjs();setMonth(today.format("YYYY-MM"));setDate(today.format("YYYY-MM-DD"));setActiveNote(null)}
 async function submit(){if(!author.trim()||!title.trim()||!content.trim())return;setSaving(true);setError("");try{const saved=await addHandoff({id:crypto.randomUUID(),handoff_date:date,author:author.trim(),title:title.trim(),content:content.trim(),created_at:new Date().toISOString()});setRecords(v=>[saved,...v]);setTitle("");setContent("");setComposing(false)}catch(e){setError(e instanceof Error?e.message:"인수인계를 저장하지 못했습니다.")}finally{setSaving(false)}}
 async function remove(note:HandoffRecord){if(!window.confirm(`[${note.title}] 인수인계를 삭제할까요?\n삭제한 내용은 복구할 수 없습니다.`))return;setError("");try{await deleteHandoff(note.id);setRecords(v=>v.filter(item=>item.id!==note.id));setActiveNote(null)}catch(e){setError(e instanceof Error?e.message:"인수인계를 삭제하지 못했습니다.")}}
 return <main className={styles.page}><header><div className={styles.identity}><Link href="/"><Image src={logo} alt="COSMATH" priority/></Link><span><ClipboardPenLine size={17}/> 인수인계</span></div><LandingMenu/></header>
 <div className={styles.dashboard}><section className={styles.calendar}><div className={styles.calendarHead}><div className={styles.monthControl}><button onClick={()=>move(-1)} aria-label="이전 달"><ChevronLeft/></button><h1>{dayjs(`${month}-01`).format("YYYY년 M월")}</h1><button onClick={()=>move(1)} aria-label="다음 달"><ChevronRight/></button></div><button className={styles.todayButton} onClick={goToday}>오늘</button></div>
 <div className={styles.days}>{["일","월","화","수","목","금","토"].map(v=><small key={v}>{v}</small>)}{days.map(day=>{const key=day.format("YYYY-MM-DD"),count=records.filter(r=>r.handoff_date===key).length;return <button key={key} data-month={day.format("YYYY-MM")===month} data-selected={key===date} data-today={key===dayjs().format("YYYY-MM-DD")} onClick={()=>{setDate(key);setActiveNote(null)}}><span>{day.date()}</span>{count>0&&<strong>{count}건</strong>}</button>})}</div></section>
 <aside className={styles.sidePanel}><section className={styles.monthSummary}><div><span>이번 달 기록</span><strong>{records.length}<small>건</small></strong></div><div><span>인계가 있는 날</span><strong>{activeDays}<small>일</small></strong></div></section>
 <section className={styles.feed}><div className={styles.feedHead}><div><p>DAILY HANDOFF</p><h2>{dayjs(date).format("M월 D일")}</h2><span>{daily.length?`${daily.length}건의 인수인계`:"등록된 내용 없음"}</span></div><button onClick={()=>setComposing(true)} aria-label="새 인수인계 작성" title="새 인수인계 작성"><Plus/></button></div>{error&&<div className={styles.error}>{error}</div>}{loading?<div className={styles.empty}><Loader2 className="animate-spin"/></div>:!daily.length?<div className={styles.empty}><ClipboardPenLine/><p>이 날짜에 등록된<br/>인수인계가 없습니다.</p></div>:<div className={styles.notes}>{daily.map(note=><button key={note.id} className={styles.noteTitle} onClick={()=>setActiveNote(note)}><span>{note.title}</span><small>{dayjs(note.created_at).format("HH:mm")}</small><ChevronRight/></button>)}</div>}</section></aside></div>
 {activeNote&&<div className={styles.modal} onMouseDown={e=>{if(e.target===e.currentTarget)setActiveNote(null)}}><article className={styles.noteDetail}><button className={styles.closeButton} onClick={()=>setActiveNote(null)} aria-label="인수인계 상세 닫기"><X/></button><p>HANDOFF DETAIL</p><span>{dayjs(activeNote.handoff_date).format("YYYY년 M월 D일")}</span><h2>{activeNote.title}</h2><div className={styles.noteMeta}><i>{activeNote.author.slice(0,1)}</i><div><strong>{activeNote.author}</strong><small>{dayjs(activeNote.created_at).format("HH:mm")}</small></div></div><p className={styles.noteContent}>{activeNote.content}</p><button className={styles.deleteButton} onClick={()=>void remove(activeNote)}><Trash2/> 삭제</button></article></div>}
 {composing&&<div className={styles.modal} onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setComposing(false)}}><aside className={styles.composer}><button className={styles.closeButton} onClick={()=>setComposing(false)} disabled={saving} aria-label="작성 창 닫기"><X/></button><p>NEW HANDOFF</p><h2>인수인계 작성</h2><span>{dayjs(date).format("YYYY년 M월 D일")}</span><label>작성자<input value={author} maxLength={100} onChange={e=>setAuthor(e.target.value)} placeholder="선생님 또는 조교 이름"/></label><label>제목<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)} placeholder="핵심 내용을 짧게 입력"/></label><label>내용<textarea value={content} maxLength={5000} onChange={e=>setContent(e.target.value)} placeholder="특이사항, 참고사항, 다음 담당자가 확인할 내용을 입력하세요."/></label>{error&&<div className={styles.error}>{error}</div>}<button className={styles.submitButton} disabled={saving||!author.trim()||!title.trim()||!content.trim()} onClick={()=>void submit()}>{saving?<Loader2 className="animate-spin"/>:<Send/>} 등록</button></aside></div>}
 </main>}
