"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Image from "next/image"; import Link from "next/link"; import dayjs from "dayjs";
import {CalendarDays,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,Loader2,Save,Users} from "lucide-react";
import logo from "../../../public/logo.png"; import {loadStudents,loadWrongAnswers,saveWrongAnswer} from "../../lib/report-storage";
import type {StudentGroup} from "../../types/student"; import type {WrongAnswerRecord} from "../../types/wrong-answer"; import styles from "./errors.module.css";
import LandingMenu from "../../components/LandingMenu";

function CompletionControl({completed,disabled,onClick}:{completed:boolean;disabled:boolean;onClick:()=>void}) {
 return <div className={styles.completion}>
  {completed ? <div role="status" className={styles.celebrate}><CheckCircle2/><strong>오답 완료!</strong><span>모두 끝냈어요. 수고했어요!</span></div>
    : <p>문제 수를 입력하지 않아도 완료할 수 있어요.</p>}
  <button type="button" disabled={disabled} className={styles.save} onClick={onClick}>{completed?"완료 취소":"✓ 오답 완료"}</button>
 </div>;
}

export default function ErrorsPage(){
 const [groups,setGroups]=useState<StudentGroup[]>([]),[records,setRecords]=useState<WrongAnswerRecord[]>([]),[selectedIds,setSelectedIds]=useState<string[]>([]),[expandedGroups,setExpandedGroups]=useState<string[]>([]),[studentId,setStudentId]=useState("");
 const [date,setDate]=useState(()=>dayjs().format("YYYY-MM-DD")),[month,setMonth]=useState(()=>dayjs().format("YYYY-MM"));
 const [total,setTotal]=useState(0),[corrected,setCorrected]=useState(0),[memo,setMemo]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [gs,rs]=await Promise.all([loadStudents(),loadWrongAnswers(month)]);const ids=gs.flatMap(g=>g.students.map(s=>s.id));setGroups(gs);setRecords(rs);setExpandedGroups(v=>v.filter(id=>gs.some(g=>g.id===id)));setSelectedIds(v=>v.filter(id=>ids.includes(id)));setStudentId(v=>ids.includes(v)?v:"")}catch(e){setError(e instanceof Error?e.message:"오답 기록을 불러오지 못했습니다.")}finally{setLoading(false)}},[month]);
 useEffect(()=>{void refresh()},[refresh]);
 const students=useMemo(()=>groups.flatMap(g=>g.students.map(s=>({...s,group:g.group}))),[groups]); const chosen=students.filter(s=>selectedIds.includes(s.id)); const current=students.find(s=>s.id===studentId); const record=records.find(r=>r.student_id===studentId&&r.record_date===date);
 useEffect(()=>{setTotal(record?.total_wrong??0);setCorrected(record?.corrected_count??0);setMemo(record?.memo??"")},[record,studentId,date]);
 const days=useMemo(()=>{const start=dayjs(`${month}-01`).startOf("week");return Array.from({length:42},(_,i)=>start.add(i,"day"))},[month]); const daily=chosen.map(student=>({student,record:records.find(r=>r.student_id===student.id&&r.record_date===date)})); const summary=daily.reduce((a,v)=>({total:a.total+(v.record?.total_wrong??0),corrected:a.corrected+(v.record?.corrected_count??0)}),{total:0,corrected:0});
 function toggle(id:string,on:boolean){const next=on?[...new Set([...selectedIds,id])]:selectedIds.filter(v=>v!==id);setSelectedIds(next);setStudentId(v=>on?id:v===id?next[0]??"":v)} function moveMonth(n:number){const next=dayjs(`${month}-01`).add(n,"month");setMonth(next.format("YYYY-MM"));setDate(next.format("YYYY-MM-DD"))}
 async function save(completed=record?.completed??false){if(saving||loading)return;if(!studentId||corrected>total){setError("수정 완료 문제 수는 전체 오답 수를 넘을 수 없습니다.");return}setSaving(true);setError("");try{const saved=await saveWrongAnswer({id:record?.id??crypto.randomUUID(),student_id:studentId,record_date:date,total_wrong:total,corrected_count:corrected,memo:memo.trim(),version:record?.version??0,completed});setRecords(v=>[...v.filter(r=>r.id!==saved.id),saved])}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.")}finally{setSaving(false)}}
 return <main className={styles.page}><header><div className={styles.identity}><Link href="/"><Image src={logo} alt="COSMATH" priority/></Link><span><CalendarDays size={17}/> 오답 관리</span></div><LandingMenu/></header><fieldset disabled={saving} className={styles.dashboard} style={{border:0,padding:0,minWidth:0}}>
 <aside className={styles.roster}><div className={styles.rosterTitle}><h2>반별 학생</h2><small>{selectedIds.length}명 선택</small></div>{groups.map(g=>{const ids=g.students.map(s=>s.id),all=ids.length>0&&ids.every(id=>selectedIds.includes(id)),expanded=expandedGroups.includes(g.id);return <section key={g.id}><div className={styles.groupHead}><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=ids.some(id=>selectedIds.includes(id))&&!all}} onChange={e=>{const next=e.target.checked?[...new Set([...selectedIds,...ids])]:selectedIds.filter(id=>!ids.includes(id));setSelectedIds(next);setStudentId(v=>e.target.checked&&ids[0]?ids[0]:next.includes(v)?v:next[0]??"")}}/><button aria-expanded={expanded} onClick={()=>setExpandedGroups(v=>expanded?v.filter(id=>id!==g.id):[...v,g.id])}><span>{g.group}</span><small>{g.students.length}</small><ChevronDown size={14}/></button></div>{expanded&&g.students.map(s=><div key={s.id} className={styles.studentRow} data-current={s.id===studentId}><input type="checkbox" checked={selectedIds.includes(s.id)} onChange={e=>toggle(s.id,e.target.checked)} aria-label={`${s.name} 선택`}/><button onClick={()=>selectedIds.includes(s.id)?setStudentId(s.id):toggle(s.id,true)}><i>{s.name.slice(0,1)}</i><span>{s.name}<small>{s.grade}</small></span></button></div>)}</section>})}</aside>
 <section className={styles.overview}><div className={styles.overviewHead}><div><p>DAILY PROGRESS</p><h1>{dayjs(date).format("M월 D일")} 오답 현황</h1><span>선택한 학생들의 진행 상황을 한눈에 확인하세요.</span></div><div className={styles.summary}><strong>{summary.corrected}</strong><span>/ {summary.total}문제</span><small>{daily.filter(({record:r})=>r?.completed||((r?.total_wrong??0)>0&&r?.corrected_count===r?.total_wrong)).length} / {daily.length}명 완료</small><small>{summary.total?Math.round(summary.corrected/summary.total*100):0}% 완료</small></div></div>{loading?<div className={styles.empty}><Loader2 className="animate-spin"/></div>:!chosen.length?<div className={styles.empty}><Users/><p>왼쪽에서 학생 또는 반을 선택하세요.</p></div>:<div className={styles.cards}>{daily.map(({student,record:r})=>{const t=r?.total_wrong??0,c=r?.corrected_count??0,done=r?.completed||(t>0&&c===t),rate=done?100:t?Math.round(c/t*100):0;return <button key={student.id} data-completed={done} data-current={student.id===studentId} onClick={()=>setStudentId(student.id)}><div className={styles.cardTop}><i>{student.name.slice(0,1)}</i><div><strong>{student.name}</strong><span>{student.grade} · {student.group}</span></div>{done&&<CheckCircle2/>}</div><div className={styles.cardScore}><strong>{done?"완료":c}</strong>{!done&&<span>/ {t}</span>}<em>{rate}%</em></div><div className={styles.bar}><i style={{width:`${rate}%`}}/></div><p>{r?.memo||(done?"오답을 모두 완료했어요":t?`${t-c}문제 남음`:"기록 없음")}</p></button>})}</div>}</section>
 <aside className={styles.detail}><div className={styles.miniCalendar}><div><button onClick={()=>moveMonth(-1)}><ChevronLeft/></button><strong>{dayjs(`${month}-01`).format("YYYY년 M월")}</strong><button onClick={()=>moveMonth(1)}><ChevronRight/></button></div><section>{["일","월","화","수","목","금","토"].map(v=><small key={v}>{v}</small>)}{days.map(d=>{const key=d.format("YYYY-MM-DD"),has=records.some(r=>selectedIds.includes(r.student_id)&&r.record_date===key);return <button key={key} data-month={d.format("YYYY-MM")===month} data-selected={key===date} data-record={has} onClick={()=>setDate(key)}>{d.date()}</button>})}</section></div><div className={styles.editor}>{loading?<Loader2 className="animate-spin"/>:<><p>SELECTED STUDENT</p><h2>{current?.name??"학생 선택"}</h2><span>{dayjs(date).format("YYYY년 M월 D일")}</span><CompletionControl completed={record?.completed??false} disabled={!studentId||saving||loading} onClick={()=>void save(!(record?.completed??false))}/>{!record?.completed&&<><div className={styles.score}><strong>{corrected}</strong><small>/ {total}문제</small><em>{total?Math.round(corrected/total*100):0}% 완료</em></div><div className={styles.inputs}><label>전체 오답<input type="number" min="0" value={total} onChange={e=>{const n=Math.max(0,Number(e.target.value));setTotal(n);setCorrected(v=>Math.min(v,n))}}/></label><label>수정 완료<input type="number" min="0" max={total} value={corrected} onChange={e=>setCorrected(Math.min(total,Math.max(0,Number(e.target.value))))}/></label></div></>}<label>메모<textarea value={memo} maxLength={2000} onChange={e=>setMemo(e.target.value)} placeholder="틀린 유형이나 다시 볼 내용을 기록하세요."/></label>{error&&<div role="alert" className={styles.error}>{error}</div>}<button className={styles.save} disabled={!studentId||saving} onClick={()=>void save()}>{saving?<Loader2 className="animate-spin"/>:<Save/>} 저장</button></>}</div></aside>
 </fieldset></main>}
